# js/css build 과정
FROM node:22 as node_builder

WORKDIR /var/www/html

# package.json 복사
COPY package.json package-lock.json ./
RUN npm install

# 전체 복사
COPY . .


RUN npm run build


#php + nginx
FROM php:8.2-fpm

# Nginx 설치 및 PHP 확장 프로그램 설치
RUN apt-get update && apt-get install -y \
    nginx \
    libzip-dev \
    libonig-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    jpegoptim \
    optipng \
    pngquant \
    gifsicle \
    unzip \
    git \
    curl \
    vim \
    iputils-ping \
    telnet \
    netcat-traditional \
&& rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install bcmath opcache
RUN docker-php-ext-install exif
RUN docker-php-ext-configure gd \
    --with-jpeg \
    --with-freetype \
&& docker-php-ext-install gd

# nginx 설정 파일 복사
COPY nginx/conf.d/default.conf /etc/nginx/sites-available/default

WORKDIR /var/www/html

#전체 코드 복사
COPY . .

# node build 폴더 복사
COPY --from=node_builder /var/www/html/src/public/build ./src/public/build

#라라벨 폴더 권한 설정 (src/ 경로 기준)
RUN mkdir -p src/bootstrap/cache
RUN chown -R www-data:www-data src/storage src/bootstrap/cache
RUN chmod -R 775 src/storage src/bootstrap/cache

# entrypoint 스크립트 복사 및 권한 부여
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# 스크립트 실행
CMD ["entrypoint.sh"]